title: Wateroverlast Berlijn 2017
date: 14-05-2017
attribution: 2017 Nelen & Schuurmans
background-layers:
  - title: Topografisch
    url: https://{s}.tiles.mapbox.com/v3/nelenschuurmans.iaa98k8k/{z}/{x}/{y}.png
stories:
  - title: Heavy Rain Berlin
    cover-image: https://static1.persgroep.net/volkskrant/image/d56d68c8-3622-455e-99bc-80c9821cb930?h=NGRkOWQ5MlpEVTJaRFk0WXpndE16WXlNaTAwTlRWbExUazVZbU10T0RCak9UZ3lNV05pT1RNd0x6UTRNSGd6TURn
    description: >
      Germany’s capital Berlin is hit with heavy rain and thunderstorms. The bad weather floods streets, underground metro stations and basements.
    steps:
      - title: Heavy Rain Berlin
        body: >
          Berlin 29 June 2017 – Germany’s capital Berlin is hit with heavy rain and thunderstorms. The bad weather floods streets, underground metro stations and basements. Measurements show over 150 mm of rain fell in Spandau and Wilmersdorf within just 18 hours. To put this into perspective, the monthly average rainfall in Berlin is 580 mm, so a quarter of the total yearly rainfall fell!
        position:
          latitude: 13.359375
          longitude: 52.519564
          zoom: 10
          angle: 0
        background-layers:
          - style: 'mapbox://styles/mapbox/streets-v8'
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 1
      - title: Traffic chaos and sewer overflows
        body: >
          Hours of rain, rain and nothing but rain in the German capital lead to traffic chaos and sewer overflows. The phone of the Berlin fire brigade rings non-stop. The firemen have had to respond 2500 times due to the exceptional weather conditions which the city can’t deal with. Neither the sewage system nor underground storage can deal with extreme rainfall like this.In the evening overstrained the sewage system in some parts of the city. "There have been massive overflows," authorities reported. Neither sewage nor underground storage could have absorbed the water masses. Therefore, contaminated water also ran into the Berlin waters.<hr/>
          ![](https://www.arcgis.com/sharing/rest/content/items/7ae33664443e4c6aa18e7c22378e47cd/resources/statistieken%20deutscher%20wetterdienst__1506697511832__w576.png)
        position:
          latitude: 13.359375
          longitude: 52.519564
          zoom: 14
          angle: 0
          bearing: 90
        background-layers:
          - url: https://{s}.tiles.mapbox.com/v3/nelenschuurmans.iaa98k8k/{z}/{x}/{y}.png
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 1
      - title: Statistics
        body: >
          A storm with rainfall as seen on June 29th 2017 statistically only occurs every 100 years. The month of June was, except of this extreme rain event, one of the driest ever measured in Germany. The image below shows the anomaly of the monthly precipitation. <hr/> <img src="https://www.arcgis.com/sharing/rest/content/items/7ae33664443e4c6aa18e7c22378e47cd/resources/Schermafbeelding%202017-09-30%20om%2017.51.51__1506786773608__w672.png" />
        position:
          latitude: 13.359375
          longitude: 52.519564
          zoom: 14
          angle: 20
          bearing: 120
        background-layers:
          - url: https://{s}.tiles.mapbox.com/v3/nelenschuurmans.iaa98k8k/{z}/{x}/{y}.png
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 1

  - title: Yorckstraße
    description: >
      At Yorckstraße the water level was high enough for this person take a swim on the flooded street.
    cover-image: http://www.fdportal.nijgh.nl/upload/1386318379.jpg?w=240
    steps:
      - title: Road accesibility map
        body: >
          During heavy rainfall, the water on the street can become so high that the road becomes inaccessible. The road accessibility map shows which roads stay accessible and which road are not accessible during extreme rainfall. Use the slider to gain insights.<br><br>Roads are classified as 'accessible' if there is a maximum water depth of 10 cm (green). At water depths between 10 and 30 cm, the roads are classified as 'accessible for emergency traffic' (yellow). Roads with water depths of 30 cm and more are 'inaccessible' (red). The main routes are shown thicker. <hr/> <img src="https://i.imgur.com/xYd0J5A.jpg"/>
        position:
          latitude: 13.3683765
          longitude: 52.4927665
          zoom: 15.5
          angle: 10
          bearing: 10
        background-layers:
          - style: 'mapbox://styles/mapbox/satellite-v9'
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 0.1
        foreground-layers:
          - url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-11-20T09%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
        compare:
          - wms-url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-10-20T04%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
            position:
              latitude: 13.3683765
              longitude: 52.4927665
          - wms-url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-12-20T12%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
            position:
              latitude: 13.3683765
              longitude: 52.4927665

      - title: Trautenaustraße
        body: >
          At lot of water was reported at the crossing of Trautenaustraße and Bundesallee. Streets were flooded and water flows down into the subway.
        position:
          latitude: 13.3269493
          longitude: 52.4930564
          zoom: 16.5
          angle: 10
          bearing: 90
        background-layers:
          - style: 'mapbox://styles/mapbox/satellite-v9'
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 0.1
        foreground-layers:
          - url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-11-20T09%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
        compare:
          - wms-url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-10-20T04%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
            position:
              latitude: 13.3683765
              longitude: 52.4927665
          - wms-url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-12-20T12%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
            position:
              latitude: 13.3683765
              longitude: 52.4927665

      - title: Bundesallee
        body: >
          A waterdepth map was created with 3Di by using the slider on the right you can get insight into the vulnerable parts of Berlin. Due to the large amount of water in the sewer system, manhole covers can come up. This poses great risks, as you can see in the video below. <hr/> <div class="iframe-container mj-video-by-url  fit"><iframe allowfullscreen="1" frameborder="0" height="226.6875" width="100%" data-src="//www.youtube.com/embed/TfL9t-za9iM?wmode=opaque&amp;rel=0" data-unload="true" src="//www.youtube.com/embed/TfL9t-za9iM?wmode=opaque&amp;rel=0"></iframe></div>
        position:
          latitude: 13.3272565
          longitude: 52.4896313
          zoom: 17
          angle: 0
          bearing: 0
        background-layers:
          - style: 'mapbox://styles/mapbox/satellite-v9'
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 0.1
        foreground-layers:
          - url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-11-20T09%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
        compare:
          - wms-url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-10-20T04%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
            position:
              latitude: 13.3683765
              longitude: 52.4927665
          - wms-url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-12-20T12%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
            position:
              latitude: 13.3683765
              longitude: 52.4927665


  - title: 3Di Model Berlin
    description: >
      In order to reconstruct the effects of the June 29th downpour a 3Di model has been created.
    cover-image: http://www.fdportal.nijgh.nl/upload/1386318379.jpg?w=240
    steps:
      - title: Flood reconstruction
        body: >
          In order to reconstruct the effects of the June 29th downpour a 3Di model has been created. 3Di is a user-friendly water management modelling package. We selected a number of locations in Wilmersdorf where floods have been reported.
        position:
          latitude: 13.3483765
          longitude: 52.4927665
          zoom: 12.5
          angle: 20
          bearing: 0
        background-layers:
          - style: 'mapbox://styles/mapbox/satellite-v9'
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 0.1
        foreground-layers:
          - url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-11-20T09%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
      - title: Elevation model
        body: >
          As input for this model we use a 1 m2 elevation model to analyse the evolution of the flood. The video shows the flood locations that will be discussed in the next sections. <hr/> <img src="https://media.giphy.com/media/3o7aCPxxq7wJr00qbe/giphy.gif"/> <hr/>In order to analyse the impact on accessibility we included the Berlin road network into the model. The 3Di model could further be improved if more details about the surface and sewer system were publicly available.
        position:
          latitude: 13.3483765
          longitude: 52.4927665
          zoom: 14.5
          angle: 20
          bearing: 20
        background-layers:
          - style: 'mapbox://styles/mapbox/satellite-v9'
            legend:
              - label: Danger
                color: '#ff0000'
              - label: Floodzone
                color: '#2D8ACC'
            opacity: 0.1
        foreground-layers:
          - url: https://demo.lizard.net/api/v3/wms/?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=projects%3As0000%3Aberlin_waterdepth&STYLES=Blues%3A0.025%3A0.3&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&TIME=2017-11-20T09%3A47%3A13&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}
